### ISSUE TITLE
example file where import is getting corrupted despite no error or warning

### ISSUE THREAD

**Issue by ajdamico** [BioStatMatt/sas7bdat.parso#5]
hi Matthew, loading this sas7bdat file into SPSS, this field should have eight distinct values.

![phf_seq unique values](https://cloud.githubusercontent.com/assets/216807/6476271/bda1883e-c1e1-11e4-8cf3-1c9e60566fa4.png)

sas7bdat.parso reads them in without any apparent problem -- but the result is wrong.  reproducible script below.  thanks!

```
# import this census research file
library(sas7bdat.parso)
tf <- tempfile()
download.file( "http://www.census.gov/housing/extract_files/data%20extracts/cpsasec14/pppub14_redes.sas7bdat" , tf , mode = 'wb' )

# this file is compressed, so use `parso`
x <- read.sas7bdat.parso( tf )

# about 60k records
nrow( x )

# look at the first fifty records..lots of different results here
head( x$PHF_SEQ , 50 )

# integer class
class( x$PHF_SEQ )

# there are lots of unique values
length( unique( x$PHF_SEQ ) )
# there should only be eight.
```

**Comment by BioStatMatt** [comment]
Thanks Anthony.

**Comment by harrysouthworth** [comment]
I don't even get that far. Using parso via a Java wrapper, NOT using sas7bdat.parso:

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
    The method writeRowsArray(List<Column>, Object[][]) in the type CSVDataWriter is not applicable for the arguments (List<Column>, Object)

```
at com.dcc.unsas.main.unsas.createDataFile(unsas.java:104)
at com.dcc.unsas.main.unsas.main(unsas.java:48)
```

Although that's preferable to it throwing no errors.

I'll report it to GGA but have no idea if they'll do anything.

Harry

**Comment by harrysouthworth** [comment]
Or I would, but searching for them reveals that they've disappeared...

**Comment by printsev** [comment]
Hi Anthony, could you please share the file with us again? It looks like the URL is not working. We will try to fix this in the parso's code.
Harry, have you been able to resolve your issue?

**Comment by ajdamico** [comment]
click the blue april 5 2015

https://web.archive.org/web/*/http://www.census.gov/housing/extract_files/data%20extracts/cpsasec14/pppub14_redes.sas7bdat

**Comment by harrysouthworth** [comment]
I had 2 issues. One was an error on my part. The other is that the parso csv writer doesn't handle quotes within quoted strings properly.

Thanks for taking this up. It's appreciated.

**Comment by printsev** [comment]
@harrysouthworth glad you were able to fix this, and we are working on the other issue. We do not really use the csv writer in java, but it looks like it's the only way for now to get this working in R. Sure, we will fix it.

@ajdamico we were able to reproduce this issue and we will fix it in the new release. The reason is that the number is bigger than Long.MAX_VALUE.

**Comment by printsev** [comment]
Dear all,

Finally we have put parso sources to github (https://github.com/epam/parso). We have changed the API a little bit, and the package structure (since EPAM acquired GGA Software Services). This issue is fixed in the new version (2.0-SNAPSHOT), we are working on the 2.0 release (trying to fix tricky issue with binary compression to include it into this release). We really hope to make this release happen this year.

Thanks
